<?php
$kecNama = [
    '010' => 'Dampal Selatan', '020' => 'Dampal Utara',
    '030' => 'Dondo',          '031' => 'Ogodeide',
    '032' => 'Basidondo',      '040' => 'Baolan',
    '041' => 'Lampasio',       '050' => 'Galang',
    '060' => 'Tolitoli Utara', '061' => 'Dako Pemean',
];

// Data petugas dari email fix.xlsx: email → [nama, kec_code, kecamatan, desa]
$emailData = [
    'wirtakwir8@gmail.com'           => ['nama'=>'Takwir','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'nurazizalakoro@gmail.com'        => ['nama'=>'Nuraziza','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'sugengarrauf@gmail.com'          => ['nama'=>'Sugeng. A','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'DIULE'],
    'lyliburhan99@gmail.com'          => ['nama'=>'Eriyanti S','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'PINJAN'],
    'rahmiagussalim43@gmail.com'      => ['nama'=>'Rahmi Agussalim','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'DIULE'],
    'mukranumran@gmail.com'           => ['nama'=>'Mukran','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'LAKUAN TOLITOLI'],
    'azizanihru@gmail.com'            => ['nama'=>'Aziza','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'ramnitolis2023@gmail.com'        => ['nama'=>'RAMNI','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'fitri.ani0@yahoo.com'            => ['nama'=>'Fitriani','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'PINJAN'],
    'ahmadsumitro96@gmail.com'        => ['nama'=>'Ahmad','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'PINJAN'],
    'sriwahyunimakkuraga@gmail.com'   => ['nama'=>'Sri wahyuni','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'GALUMPANG'],
    'sahratulaini99@gmail.com'        => ['nama'=>'SAHRATUL AINI','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'DUNGINGIS'],
    'hashari.h.hh@gmail.com'          => ['nama'=>'Hashari','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'KAPAS'],
    'armina160298@gmail.com'          => ['nama'=>'Armina','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'LINGADAN'],
    'ulfiani.ani992@gmail.com'        => ['nama'=>'ULPIANI RUSNO','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'LINGADAN'],
    'dewisosiartika@gmail.com'        => ['nama'=>'DEWI SOSIARTIKA','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'GALUMPANG'],
    'syahdigalumpang@gmail.com'       => ['nama'=>'SYAHDI','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'GALUMPANG'],
    'afriantomuhsen756@gmail.com'     => ['nama'=>'Afrianto','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'albarbar24@gmail.com'            => ['nama'=>'ALBAR','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'STADONG'],
    'halfinafhyna@gmail.com'          => ['nama'=>'HALFINA','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'TAMPIALA'],
    '02lovelymore@gmail.com'          => ['nama'=>'FARADHIBA','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'farida181198@gmail.com'          => ['nama'=>'Farida','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'karnitanita808@gmail.com'        => ['nama'=>'KARNITA','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'BAMBAPULA'],
    'meyandris29@gmail.com'           => ['nama'=>'MEYSAHDI. A','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'muliantii1996@gmail.com'         => ['nama'=>'Mulianti Maulana','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'SESE'],
    'misnajo1@gmail.com'              => ['nama'=>'Misna','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'meghanaharudin763@gmail.com'     => ['nama'=>'Sulastri','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'BANAGAN'],
    'wahyudiforester6@gmail.com'      => ['nama'=>'WAHYUDI MOH HARIS','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'SESE'],
    'iffatpratama321@gmail.com'       => ['nama'=>'Moh. Iffat Widad Pratama','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'ffara8629@gmail.com'             => ['nama'=>'Farah','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANGI'],
    'faisalchaldo@gmail.com'          => ['nama'=>'Moh faisal','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'nurulayustina198@gmail.com'      => ['nama'=>'Nurul Ayustina','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'trimuliadi00@gmail.com'          => ['nama'=>'TRI MULIADI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'latumpu77@gmail.com'             => ['nama'=>'yusuf','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'mutmainna140201@gmail.com'       => ['nama'=>'Mutmainna','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'nurdianadina1220@gmail.com'      => ['nama'=>'Nurdiana Zaharman','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'saniyyah0410@gmail.com'          => ['nama'=>'SANIYYAH NUR PURNAMA S.Sos','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'ayusyawitri22@gmail.com'         => ['nama'=>'SRI DEVI AYU SYAWITRI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'usuci8993@gmail.com'             => ['nama'=>'Suci Safitry','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'nurhajra08092019@gmail.com'      => ['nama'=>'NUR HAJRA SYAFRUDDIN','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'indahade247@gmail.com'           => ['nama'=>'ADE INDAH PUSPITA SARI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'ahmaadtlz17@gmail.com'           => ['nama'=>'AHMAD SAID','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'fitriyantimarhalil@gmail.com'    => ['nama'=>'Fitriyanti','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'umijarnawi@gmail.com'            => ['nama'=>'JUMIATI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'LELEAN NONO'],
    'wulandarisb981@gmail.com'        => ['nama'=>'Wulandari S. Butudoka','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'nanadjapara10@gmail.com'         => ['nama'=>'Nurhasanah','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'raramutiara353@gmail.com'        => ['nama'=>'ANDI MUTIARA ISTIQHAMARANI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'SIDOARJO'],
    'fitriyawatitadore@gmail.com'     => ['nama'=>'FITRIYAWATI NH HANS TADORE','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'SIDOARJO'],
    'astuti7061992@gmail.com'         => ['nama'=>'Tri astuti','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BUNTUNA'],
    'deliyhana2022@gmail.com'         => ['nama'=>'SRI DELY','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'mohfajrin219@gmail.com'          => ['nama'=>'Moh. Fajrin','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'maulana022007@gmail.com'         => ['nama'=>'MOH. RISKY MAULANA','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'rosnirauf@gmail.com'             => ['nama'=>'ROSNI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'wahyuniarfan1989@gmail.com'      => ['nama'=>'Sri wahyuni syaripudin','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'rizkika357@gmail.com'            => ['nama'=>'Rizkyka Putri','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'septiyadimerdekap@gmail.com'     => ['nama'=>'SEPTYADI MERDEKA PUTRA','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'sriwahyunikmajah@gmail.com'      => ['nama'=>'SRI WAHYUNI K.MAJAH','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'zhaafirah030501@gmail.com'       => ['nama'=>'Yusriyyah Zhaafirah','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'nuraida25041981@gmail.com'       => ['nama'=>'Nuraida','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'SIDOARJO'],
    'ramsaanca177@gmail.com'          => ['nama'=>'RAMSA','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'BASI'],
    'fajarirawan0501@gmail.com'       => ['nama'=>'Fajar irawan','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'KAYULOMPA'],
    'yusnihidayah21@gmail.com'        => ['nama'=>'Yusni Hidayah','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'BASI'],
    'tinasuhar65@gmail.com'           => ['nama'=>'Suhartina','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'LABONU'],
    'irnawati170792@gmail.com'        => ['nama'=>'IRNAWATI ASHAR','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'GALUMPANG'],
    'yuyundiahpratiwi2397@gmail.com'  => ['nama'=>'YUYUN DIAH PRATIWI','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OGOMATANANG'],
    'niluhulan@gmail.com'             => ['nama'=>'Ni Luh Ulan Sariani','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'SIBEA'],
    'dessy261297@gmail.com'           => ['nama'=>'DESSY PUTRI AMALIA','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'ikkenvs@gmail.com'               => ['nama'=>'Ikke Nur Vita Sari','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'LAMPASIO'],
    'nurinsyan14@gmail.com'           => ['nama'=>'NURINSYAN','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OYOM'],
    'animariany16@gmail.com'          => ['nama'=>'Mariani','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'moh.reza992@gmail.com'           => ['nama'=>'MOHAMMAD REZA','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'OGOMOLI'],
    'yunusmuh580@gmail.com'           => ['nama'=>'Muh. Yunus','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'anif73599@gmail.com'             => ['nama'=>'Pitriani','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'hasnirizal06@gmail.com'          => ['nama'=>'Hasni Rizal','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'SANDANA'],
    'tutiwinarni628@gmail.com'        => ['nama'=>'Tuti Winarni','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'LAKATAN'],
    'tinatangkuman102@gmail.com'      => ['nama'=>'Hartina','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'BAJUGAN'],
    'lelaalfiana@gmail.com'           => ['nama'=>'Alfiana','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'iqbalm2410@gmail.com'            => ['nama'=>'Moh Iqbal','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'moh.khairaat@gmail.com'          => ['nama'=>'Moh. Mulkan','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'BAJUGAN'],
    'suhradinad@gmail.com'            => ['nama'=>'SUHRADINA','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'liaa301102@gmail.com'            => ['nama'=>'Lia Andriani','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'LANTAPAN'],
    'indrayaniburhanudin@gmail.com'   => ['nama'=>'Indrayani Burhanudin','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'AUNG'],
    'smia89864@gmail.com'             => ['nama'=>'Salmia','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KINOPASAN'],
    'srihardiyantii26@gmail.com'      => ['nama'=>'Sri Hardiyanti','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'SANDANA'],
    'aliflibiya254@gmail.com'         => ['nama'=>'Alif Libiya Melani','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    '082293jya@gmail.com'             => ['nama'=>'Nurjaya','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOWELE BUGA'],
    'budimann225@gmail.com'           => ['nama'=>'Budiman','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'LOBUO'],
    'deviarni01@gmail.com'            => ['nama'=>'Deviana','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'darachandra2@gmail.com'          => ['nama'=>'Chandra','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'annisarahma16102002@gmail.com'   => ['nama'=>'Annisa Rahmayanti','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALALA'],
    'melinndaa26@gmail.com'           => ['nama'=>'Melinda','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'ammargonggol@gmail.com'          => ['nama'=>'Muammar','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'riswanaswaludin4@gmail.com'      => ['nama'=>'Moh. Riswan Aswaludin','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'novianivhy34@gmail.com'          => ['nama'=>'Noviani','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOWELE BUGA'],
    'sittihajarsalam63@gmail.com'     => ['nama'=>'Siti Hajar','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'ANGGASAN'],
    'susantitolis2018@gmail.com'      => ['nama'=>'Susanti','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'LAIS'],
    'tritakdir753@gmail.com'          => ['nama'=>'TRI TAKDIR U SYAH','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALOMBA'],
    'puspitasaritolis2020@gmail.com'  => ['nama'=>'Puspita Sari','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOWELE BUGA'],
    'asdardahyar@gmail.com'           => ['nama'=>'ASDAR','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'LABUAN LOBO'],
    'nvtasariy@gmail.com'             => ['nama'=>'Novita sari','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BILO'],
    'nia.060803@gmail.com'            => ['nama'=>'Asmania','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'LABUAN LOBO'],
    '2000padlia@gmail.com'            => ['nama'=>'PADLIA','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'KAMALU'],
    'rhiahijria994@gmail.com'         => ['nama'=>'Fahrin','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BILO'],
    'fitryani0102@gmail.com'          => ['nama'=>'Fitriani','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BILO'],
    'ibrahimanthonie0707@gmail.com'   => ['nama'=>'Ibrahim anthonie','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'PULIAS'],
    'fatihfatir97@gmail.com'          => ['nama'=>'Marta','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BATUILO'],
    'zeynzacky2023@gmail.com'         => ['nama'=>'MOHAMAD YASIR','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BATUILO'],
    'nasriajamrin2002@gmail.com'      => ['nama'=>'Nasria','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BILO'],
    'rahmatialukman27@gmail.com'      => ['nama'=>'RAHMATIA','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'SAMBUJAN'],
    'noviawulandari129@gmail.com'     => ['nama'=>'Novia Edi Wulandari','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'BUGA'],
    'hasrianihamzah579@gmail.com'     => ['nama'=>'Hasriani','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'PADDUMPU'],
    'misnasupriadi935@gmail.com'      => ['nama'=>'MISNA','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'DONGKO'],
    'zulkifliusman1997@gmail.com'     => ['nama'=>'ZULKIFLI USMAN','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'PALLAKAWE'],
    'sasmita08082004@gmail.com'       => ['nama'=>'Sasmita','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'TAMPIALA'],
    'nasirhartati77@gmail.com'        => ['nama'=>'Hartati','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'TAMPIALA'],
    'magfira066@gmail.com'            => ['nama'=>'MAGFIRA','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'TAMPIALA'],
    'ikamulyady@gmail.com'            => ['nama'=>'Kartika','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'SONI'],
    'abbdulsamad61@gmail.com'         => ['nama'=>'Abd Samad','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'TAMPIALA'],
    'reniamalia978@gmail.com'         => ['nama'=>'RENI AMALIA','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'SONI'],
    'irayuliastari1@gmail.com'        => ['nama'=>'Ira yuliastari','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'BANGKIR'],
    'sardianaj@gmail.com'             => ['nama'=>'Sardiana','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'PADDUMPU'],
    'damsel.bangkir43@gmail.com'      => ['nama'=>'Rezkiyani yaya','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'BANGKIR'],
    'siskaikha310@gmail.com'          => ['nama'=>'Siska','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'LEMBA HARAPAN'],
    'riniarditasari18@gmail.com'      => ['nama'=>'Rini Ardita Sari','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'BANGKIR'],
    'rahmatiabahri@gmail.com'         => ['nama'=>'Rahmatia','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'PUSE'],
    'kadirmankadir3@gmail.com'        => ['nama'=>'Kadirman','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'LEMBA HARAPAN'],
    'srisutanti4767@gmail.com'        => ['nama'=>'SRI SUTANTi','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'KAPAS'],
    'qolbirahmaaulia@gmail.com'       => ['nama'=>'Rahma Aulia','kec_code'=>'061','kecamatan'=>'DAKO PEMEAN','desa'=>'GALUMPANG'],
    'hasrianisri061@gmail.com'        => ['nama'=>'Hasriani','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'SONI'],
    'andimariam249@gmail.com'         => ['nama'=>'Andi mariam','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'LAKUAN TOLITOLI'],
    'andanghamdan51@gmail.com'        => ['nama'=>'HAMDAN','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'SIMATANG TANJUNG'],
    'silfaniagus27@gmail.com'         => ['nama'=>'Silfani','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'esiastarita394@gmail.com'        => ['nama'=>'Esi Astarita','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'BAMBAPULA'],
    'astarita832@gmail.com'           => ['nama'=>'IRANINGSIH','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'BAMBAPULA'],
    'winisudarmin23@gmail.com'        => ['nama'=>'WINI','kec_code'=>'020','kecamatan'=>'DAMPAL UTARA','desa'=>'OGOTUA'],
    'mokhoramli@gmail.com'            => ['nama'=>'Harmoko','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'miftahjannah1924@gmail.com'      => ['nama'=>'Miftahul Jannah','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALALA'],
    'dhevyaries07@gmail.com'          => ['nama'=>'Devi afrianingsi','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALOMBA'],
    'miftachulannah@gmail.com'        => ['nama'=>'MIFTAHUL JANNAH','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOWELE'],
    'tasyi679@gmail.com'              => ['nama'=>'Natasya','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOWELE BUGA'],
    'lukmanpramuka13@gmail.com'       => ['nama'=>'LUKMAN','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALOMBA'],
    'syafiahfiah232@gmail.com'        => ['nama'=>'Syafiah','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALOMBA'],
    'trisyetrisnawati01@gmail.com'    => ['nama'=>'Trisye Trisnawati','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'wana061101@gmail.com'            => ['nama'=>'NISWANA','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'OGOGILI'],
    'yunianang04@gmail.com'           => ['nama'=>'Wahyuni','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'MALOMBA'],
    'pianoviani2911@gmail.com'        => ['nama'=>'Noviani','kec_code'=>'030','kecamatan'=>'DONDO','desa'=>'TINABOGAN'],
    'bluebubblegum201@gmail.com'      => ['nama'=>'AFIFAH TRI HUMAIRAH','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'TONDO'],
    'hallowdaya@gmail.com'            => ['nama'=>'Nurhidayah','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'TONDO'],
    'abjadalam9@gmail.com'            => ['nama'=>'Sudirman','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'PULIAS'],
    'desiraihana8896@gmail.com'       => ['nama'=>'Desi Raihana','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OYOM'],
    'ramlicovid@gmail.com'            => ['nama'=>'RAMLI','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'KABETAN'],
    'tinaahada@gmail.com'             => ['nama'=>'Siti hartina','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'nrfaisah24@gmail.com'            => ['nama'=>'Nur faisah','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OYOM'],
    'samrins365@gmail.com'            => ['nama'=>'Samrin','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'SIBALUTON'],
    'ekarezkiana11@gmail.com'         => ['nama'=>'Eka Rezkiana S. N. Daud','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'KONKOMOS'],
    'lisstiawati10@gmail.com'         => ['nama'=>'Lis Setyawati','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'GINUNGGUNG'],
    'ikkireskiikkireski199@gmail.com'  => ['nama'=>'RESKI','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'PADDUMPU'],
    'irhamdhanial23@gmail.com'        => ['nama'=>'M IRHAM','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'LABONU'],
    'abdulbasar181010129@gmail.com'   => ['nama'=>'ABDUL BASAR','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'nurinurhasanah46@gmail.com'      => ['nama'=>'Nuri Nurhasanah','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'sartika.awaludin@gmail.com'      => ['nama'=>'Sartika','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'moh.haris2025@gmail.com'         => ['nama'=>'Moh Haris','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'MUARA BESAR'],
    'rizalreynaldy.rr@gmail.com'      => ['nama'=>'MOH. RIZAL REYNALDY','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'sindy.tolis22@gmail.com'         => ['nama'=>'SINDI AMELIA','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'mirzabahtiar87@gmail.com'        => ['nama'=>'MIRZA','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'samitmidong@gmail.com'           => ['nama'=>'Samid','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'BASI'],
    'hasmanman836@gmail.com'          => ['nama'=>'HASMAN','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'fadeld76@gmail.com'              => ['nama'=>'Moh Fadel','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'tolutjayamandiri@gmail.com'      => ['nama'=>'Leni Liana','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'marwarusno2000@gmail.com'        => ['nama'=>'Marwa Rusno','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'sayidatunnisah@gmail.com'        => ['nama'=>'SAYIDATUN NISAH','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'eetarf03@gmail.com'              => ['nama'=>'Moh. Etsyakhran','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'LAKATAN'],
    'tahwiltahir@gmail.com'           => ['nama'=>'Tahwil','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'SONI'],
    'andisingkarahmadana@gmail.com'   => ['nama'=>'ANDI SINGKA RAHMADANA','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'KAYULOMPA'],
    'yulianalatape@gmail.com'         => ['nama'=>'Yuliana','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'LALOS'],
    'delilarf3009@gmail.com'          => ['nama'=>'Delila Rizky Fauzia','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'zahraanggraini9722@gmail.com'    => ['nama'=>'ZAHRA FIRTSZA ANGGRAINI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'artalitagafur@gmail.com'         => ['nama'=>'Artalita','kec_code'=>'031','kecamatan'=>'OGODEIDE','desa'=>'KAMALU'],
    'setiawanrahmat50509@gmail.com'   => ['nama'=>'RAHMAT SETIAWAN','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'MIMBALA'],
    'yunitatolis5@gmail.com'          => ['nama'=>'Yunita Arifin','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'pong290597@gmail.com'            => ['nama'=>'EVAYANA','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'SALUMPAGA'],
    'ikhsanwiratama2025@gmail.com'    => ['nama'=>'Ikhsan','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'MIMBALA'],
    'mohikhwan826@gmail.com'          => ['nama'=>'Moh Ikhwan','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OYOM'],
    'pratiwihalil101@gmail.com'       => ['nama'=>'Pratiwi','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'NALU'],
    'ihsan.dumbo11@gmail.com'         => ['nama'=>'Ihsan','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'jalangkoteibuudin26@gmail.com'   => ['nama'=>'ANDI JUMRIANI','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'LAMPASIO'],
    'aisyahsah456@gmail.com'          => ['nama'=>'Nur Aisyah','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'BAJUGAN'],
    'kurniatirustam21@gmail.com'      => ['nama'=>'Kurniati','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'hafidzahnurul61@gmail.com'       => ['nama'=>'Hafidzah Nurul Millah. Z','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'ma147696@gmail.com'              => ['nama'=>'Moh. Agung','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'SANDANA'],
    'ikaingguti@gmail.com'            => ['nama'=>'Nurwahida H Ingguti','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'mohhamkadahlan271299@gmail.com'  => ['nama'=>'MOH HAMKA','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'KAYULOMPA'],
    'efry0222@gmail.com'              => ['nama'=>'Efriwanda','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'TIMBOLO'],
    'fadlina.linaa2003@gmail.com'     => ['nama'=>'FADLINA','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'TINIGI'],
    'nahdatulrahman@gmail.com'        => ['nama'=>'Nahdatu Rahma','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KINOPASAN'],
    'erwinpradistyaa@gmail.com'       => ['nama'=>'Erwin','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'SIBALUTON'],
    'arumijennaira1341@gmail.com'     => ['nama'=>'Mega Alvionita','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OGOMATANANG'],
    'miftahuljanna.mjii@gmail.com'    => ['nama'=>'Miftahul Janna','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KALANGKANGAN'],
    'dindaaprilya222@gmail.com'       => ['nama'=>'Dinda Aprilya','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'OGOMOLI'],
    'ernihasbi56@gmail.com'           => ['nama'=>'ERNY','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'viivikusuma@gmail.com'           => ['nama'=>'Silvie Sri Kusuma','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'fitriwahyuningsih116@gmail.com'  => ['nama'=>'Fitri Wahyu Ningsih','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'muhainiyusuf@gmail.com'          => ['nama'=>'MUHAINI YUSUF','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'KINOPASAN'],
    'ammankmuhsalman@gmail.com'       => ['nama'=>'Muhammad salman','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BUNTUNA'],
    'intanprdtha24@gmail.com'         => ['nama'=>'Intan Paraditha','kec_code'=>'032','kecamatan'=>'BASIDONDO','desa'=>'KAYULOMPA'],
    'fajaraswah53@gmail.com'          => ['nama'=>'MUH FAJAR ASWAH','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'MULIASARI'],
    'ririnmarliana1430@gmail.com'     => ['nama'=>'Ririn marliana','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'adfadilah06@gmail.com'           => ['nama'=>'Fadila','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TAMBUN'],
    'safiraramadani1999@gmail.com'    => ['nama'=>'Sapira Ramadani','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'alwizihab285@gmail.com'          => ['nama'=>'ALWI','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'GINUNGGUNG'],
    'nandapade@icloud.com'            => ['nama'=>'Albar Sukri','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'GINUNGGUNG'],
    'rinipntoh@gmail.com'             => ['nama'=>'Rini.s','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'DIULE'],
    'vhiasilvia2020@gmail.com'        => ['nama'=>'Vina silvia','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'BINONTOAN'],
    'shajaredwin@gmail.com'           => ['nama'=>'Sitti Hajar E. Dt. Amas','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'BINONTOAN'],
    'tampubolonsahala49@gmail.com'    => ['nama'=>'SAHALA TAMPUBOLON','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'niskayhabu@gmail.com'            => ['nama'=>'Niska Y. Habu','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'AUNG'],
    'wahyuliadjmallo@gmail.com'       => ['nama'=>'WAHYULIA','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'mawar191291@gmail.com'           => ['nama'=>'Mawar','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'BAJUGAN'],
    'iketutpujaastawadiputra@gmail.com' => ['nama'=>'I ketut puja astawa diputra','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'SIBEA'],
    'lisaxnx20@gmail.com'             => ['nama'=>'Sitti Nurhaliza','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'andinipontoh1@gmail.com'         => ['nama'=>'ANDINI S A PONTOH','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'DIULE'],
    'nurlindahramadhanyy06@gmail.com' => ['nama'=>'Nurlindah Ramadhany','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
    'sitierlinaarahmanerlina@gmail.com' => ['nama'=>'Siti Erlin A Rahman','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'LAKUAN TOLITOLI'],
    'gamainumaki@gmail.com'           => ['nama'=>'Ananda zesakarti pramana putra','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'PANASAKAN'],
    'jusmahwati08@gmail.com'          => ['nama'=>'Jusmahwati','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'indarwandi937@gmail.com'         => ['nama'=>'Indarwati','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'BANGKIR'],
    'musliaditolis@gmail.com'         => ['nama'=>'Sitti kurnia','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'SIBEA'],
    'agustinaxx02@gmail.com'          => ['nama'=>'Agustina','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'DONGKO'],
    'nurhasidahs125@gmail.com'        => ['nama'=>'Nurhasida HS','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'LAMPASIO'],
    'sritutialawia@gmail.com'         => ['nama'=>'SRITUTI ALAWIA','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'LAULALANG'],
    'nurnawiraazzhara@gmail.com'      => ['nama'=>'Nur Nawira Azzhara','kec_code'=>'010','kecamatan'=>'DAMPAL SELATAN','desa'=>'DONGKO'],
    'idjafar095@gmail.com'            => ['nama'=>'MUHAMMAD NURDIANSYAH S DJAFAR','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'GIO'],
    'djumaopall@gmail.com'            => ['nama'=>'ALHAMDANI','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'TUWELEY'],
    'nafilatulyulmaz@gmail.com'       => ['nama'=>'YULIANA','kec_code'=>'060','kecamatan'=>'TOLITOLI UTARA','desa'=>'PINJAN'],
    'menni010429@gmail.com'           => ['nama'=>'Sumarni','kec_code'=>'050','kecamatan'=>'GALANG','desa'=>'OGOMOLI'],
    'sridevilula991115@gmail.com'     => ['nama'=>'Sri devi','kec_code'=>'041','kecamatan'=>'LAMPASIO','desa'=>'OYOM'],
    'mohtaufanalfareza@gmail.com'     => ['nama'=>'Muh. Taufan Al Fareza','kec_code'=>'040','kecamatan'=>'BAOLAN','desa'=>'BARU'],
];

// Helper: ambil nama dari email (case-insensitive)
$getNama = fn($email) => ($emailData[strtolower($email)]['nama'] ?? $email);
